-- Pufferlean: a real-number reference model of PufferLib's RL trainer and
-- ocean environments, with bounded floating-point (bf16) approximation and
-- differential testing against the C implementation at ~/src/PufferLib.
--
-- Module layout is filled in as the formalization proceeds; see PLAN.md.
import Puffer.Basic
import Puffer.Float
import Puffer.Numeric.Bf16
import Puffer.Numeric.Reduction
import Puffer.Numeric.SinCosF
import Puffer.RL.GAE
import Puffer.RL.GAEError
import Puffer.RL.GAERuntime
import Puffer.RL.Loop
import Puffer.RL.LoopVecTrain
import Puffer.RL.LoopR
import Puffer.RL.LoopVecRollout
import Puffer.RL.LoopRPi
import Puffer.RL.LoopEpReturns
import Puffer.RL.PPO
import Puffer.RL.PPORuntime
import Puffer.RL.GaussianRuntime
import Puffer.RL.EntropyRuntime
import Puffer.RL.GAEMean
import Puffer.RL.GAEVar
import Puffer.RL.AdvNormPerturb
import Puffer.RL.GAENormTrue
import Puffer.RL.PPOTotalRuntime
import Puffer.RL.ValueLossForward
import Puffer.RL.Normalize
import Puffer.RL.NormalizeRuntime
import Puffer.RL.MuonRuntime
import Puffer.RL.MuonMatrixRuntime
import Puffer.RL.NewtonSchulzError
import Puffer.RL.NewtonSchulzTight
import Puffer.RL.SpectralBridge
import Puffer.RL.MuonScalarBound
import Puffer.RL.MuonGramBound
import Puffer.RL.MatrixEmbed
import Puffer.RL.MuonCoeffFloat
import Puffer.RL.NewtonSchulzFloat
import Puffer.RL.FrobFoldAccuracy
import Puffer.RL.NewtonSchulzSeedClosed
import Puffer.RL.MuonComposition
import Puffer.RL.MuonCompositionMatrix
import Puffer.RL.NewtonSchulzTransport
import Puffer.RL.MuonCompositionFloat
import Puffer.RL.NewtonSchulzCompMirror
import Puffer.RL.NewtonSchulzFull
import Puffer.RL.NewtonSchulzRunnable
import Puffer.RL.NewtonSchulzFrobBridge
import Puffer.RL.NewtonSchulzNormTower
import Puffer.RL.NewtonSchulzDemo
import Puffer.RL.MuonStepBound
import Puffer.RL.MuonUpdateBound
import Puffer.RL.MuonTrainBound
import Puffer.RL.MuonTrainLoop
import Puffer.RL.MuonStepDemo
import Puffer.RL.NewtonSchulzAssembly
import Puffer.RL.ForwardRuntime
import Puffer.RL.UpdateRuntime
import Puffer.RL.UpdateADBound
import Puffer.RL.ReverseUpdateBound
import Puffer.RL.NetUpdateBound
import Puffer.RL.ReverseNetUpdateBound
import Puffer.RL.AdamStep
import Puffer.RL.AdamVector
import Puffer.RL.AdamFinite
import Puffer.RL.AdamExecBridge
import Puffer.RL.SoftmaxBound
import Puffer.RL.SoftmaxExec
import Puffer.RL.LayerNormBound
import Puffer.RL.LayerNormExec
import Puffer.RL.ForwardExec
import Puffer.RL.PolicyBound
import Puffer.RL.LogPolicyBound
import Puffer.RL.PolicyKL
import Puffer.RL.ActorCriticBound
import Puffer.RL.AdvNormBound
import Puffer.RL.PPOPerturb
import Puffer.RL.PPOValuePerturb
import Puffer.RL.ACObjectivePerturb
import Puffer.RL.EntropyPerturb
import Puffer.RL.PPOTotalPerturb
import Puffer.RL.LogSumExpBound
import Puffer.RL.RatioForward
import Puffer.RL.KLForward
import Puffer.RL.EntropyForward
import Puffer.RL.SurrogateForward
import Puffer.RL.SurrogateExpr
import Puffer.RL.SoftmaxExpr
import Puffer.RL.LinearLayerExpr
import Puffer.RL.MLPExpr
import Puffer.RL.ValueEntropyExpr
import Puffer.RL.PPOObjectiveExpr
import Puffer.RL.PPOObjectiveGrad
import Puffer.RL.EntropyGradExpr
import Puffer.RL.SurrogateGradExpr
import Puffer.RL.LogSoftmaxBudgetExpr
import Puffer.RL.LogSoftmaxValueBudgetExpr
import Puffer.RL.RatioGradExpr
import Puffer.RL.MLPDepthExpr
import Puffer.RL.DMLPExpr
import Puffer.RL.ActiveRegionExpr
import Puffer.RL.MLPDepthNExpr
import Puffer.RL.SurrogateConcreteExpr
import Puffer.RL.EntropyConcreteExpr
import Puffer.RL.LogSoftmaxBudgetBundle
import Puffer.RL.PPOTotalGradConcrete
import Puffer.RL.WholeRunInterval
import Puffer.RL.WholeRunFromC26
import Puffer.RL.RegionInvariance
import Puffer.RL.TrajReachability
import Puffer.RL.ClipBarrier
import Puffer.RL.EntropyBarrier
import Puffer.RL.HTrapAssembly
import Puffer.RL.BudgetDischarge
import Puffer.RL.ObjectiveGradMag
import Puffer.RL.RunnableRegion
import Puffer.RL.MuonAscentBridge
import Puffer.RL.FiniteBound
import Puffer.RL.NewtonSchulzLipschitz
import Puffer.RL.ForwardFinite
import Puffer.RL.ClipContraction
import Puffer.RL.NewtonSchulzMatrixLipschitz
import Puffer.RL.LossFinite
import Puffer.RL.ContractionConstant
import Puffer.RL.NewtonSchulzIterate
import Puffer.RL.LossForwardFinite
import Puffer.RL.WeightDecayFixedPoint
import Puffer.RL.MuonStepLipschitz
import Puffer.RL.PPOLossScalar
import Puffer.RL.BanachConcrete
import Puffer.RL.NewtonSchulzStable
import Puffer.RL.BackwardFinite
import Puffer.RL.WdNatFinBridge
import Puffer.RL.NewtonSchulzBall
import Puffer.RL.GradOpnormLip
import Puffer.RL.MuonUpdateFinite
import Puffer.RL.MuonBallWholeRun
import Puffer.RL.SupOpnormBridge
import Puffer.RL.WholeRunFinite
import Puffer.RL.ReshapeBridge
import Puffer.RL.RealMatrixBall
import Puffer.RL.WdRunFinite
import Puffer.RL.ADTapeFinite
import Puffer.RL.MuonRealCompose
import Puffer.RL.MarginCheck
import Puffer.RL.CompTapeWeights
import Puffer.RL.LogTapeFinite
import Puffer.RL.TraceCheck
import Puffer.RL.FiniteHorizonRun
import Puffer.RL.CompTapeLog
import Puffer.RL.FloatFloor
import Puffer.RL.CompTapeFloor
import Puffer.RL.BudgetEval
import Puffer.RL.PipelineDemo
import Puffer.RL.SweepEval
import Puffer.RL.RunConstEval
import Puffer.RL.VerifyTrace
import Puffer.Check.Core
import Puffer.Check.Tail
import Puffer.Check.Parse
import Puffer.RL.CheckBridge
import Puffer.RL.RunnableDemo
import Puffer.RL.FloorEval
import Puffer.RL.MuonRunEval
import Puffer.RL.MuonBallRunFinite
import Puffer.RL.FullInstantiation
import Puffer.RL.ClipInteriorExpr
import Puffer.RL.WeightDecayInterval
import Puffer.RL.StepIntervalFromC1
import Puffer.RL.EntropyBudgetUniform
import Puffer.RL.PPOTotalForward
import Puffer.RL.BackwardLoopReduction
import Puffer.RL.ReturnsInvariant
import Puffer.RL.GAEInvariant
import Puffer.RL.GAEValueTargets
import Puffer.RL.GAEInputPerturb
import Puffer.RL.GAEDeltaError
import Puffer.RL.GAETrue
import Puffer.Float.AutoDiffR
import Puffer.Float.ADReverse
import Puffer.Float.ADReverseError
import Puffer.Float.ADReverseErrorTight
import Puffer.Float.ADReverseBridge
import Puffer.Optim.Muon
import Puffer.Net.Forward
